CREATE TABLE `ai_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(255) NOT NULL,
	`company` varchar(255) NOT NULL,
	`jobTitle` varchar(100),
	`phone` varchar(50),
	`companySize` varchar(50),
	`industry` varchar(100),
	`globalScore` int NOT NULL,
	`strategyScore` int NOT NULL,
	`dataScore` int NOT NULL,
	`technologyScore` int NOT NULL,
	`talentScore` int NOT NULL,
	`governanceScore` int NOT NULL,
	`cultureScore` int NOT NULL,
	`maturityLevel` varchar(50) NOT NULL,
	`responses` text NOT NULL,
	`pdfDownloaded` int NOT NULL DEFAULT 0,
	`pdfDownloadedAt` timestamp,
	`consultationRequested` int NOT NULL DEFAULT 0,
	`consultationRequestedAt` timestamp,
	`utmSource` varchar(100),
	`utmMedium` varchar(100),
	`utmCampaign` varchar(100),
	CONSTRAINT `ai_assessments_id` PRIMARY KEY(`id`)
);
