CREATE TABLE `leo_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(255) NOT NULL,
	`page` varchar(100) NOT NULL,
	`messagesCount` int NOT NULL DEFAULT 0,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`lastActivityAt` timestamp NOT NULL DEFAULT (now()),
	`endedAt` timestamp,
	`durationSeconds` int DEFAULT 0,
	`userEmail` varchar(255),
	`userName` varchar(255),
	`emailCaptured` int NOT NULL DEFAULT 0,
	`emailCapturedAt` timestamp,
	`userAgent` text,
	`referrer` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leo_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `leo_sessions_sessionId_unique` UNIQUE(`sessionId`)
);
